apiVersion: v1
kind: Service
metadata:
  name: devops-platform-service
spec:
  type: LoadBalancer
  selector:
    app: devops-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000